name = 'david m'
# print(len(name))
# print(name.find('d'))
# print(name.capitalize())
# print(name.upper())
# print(name.isdigit())
# print(name.isalpha())
# print(name.isalnum())
# print(name.count('d'))
print(name.replace('m', 'M'))
print(name)
